# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
max_subarray_sum_naive_Rcpp <- function(arr) {
    .Call(`_MaximumSubarray_max_subarray_sum_naive_Rcpp`, arr)
}

#' @export
max_subarray_sum_opt_Rcpp <- function(arr) {
    .Call(`_MaximumSubarray_max_subarray_sum_opt_Rcpp`, arr)
}

#' @export
max_subarray_rectangle_naive_Rcpp <- function(mat) {
    .Call(`_MaximumSubarray_max_subarray_rectangle_naive_Rcpp`, mat)
}

#' @export
max_subarray_rectangle_opt_Rcpp <- function(mat) {
    .Call(`_MaximumSubarray_max_subarray_rectangle_opt_Rcpp`, mat)
}

